import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { signIn } from "next-auth/react";
import { useSession } from "next-auth/react";
import styles from "../../styles/signin.module.css";
import Link from "next/link";

const signin = () => {
  const router = useRouter();
  const { status, data } = useSession();

  const [userInfo, setUserInfo] = useState({ text: "", password: "" });
  const [alert, setAlert] = useState("");

  const handleSubmit = async (e) => {
    // validate user
    e.preventDefault();

    let result = false;

    if (userInfo.text === "" || userInfo.password === "") {
      setAlert("Fill up inputs!");
      result = true;
    }

    if (!result) {
      try {
        const res = await signIn("credentials", {
          text: userInfo.text,
          password: userInfo.password,
          redirect: false,
        });

        if (!res.ok) {
          setAlert("Invalid credentials!");
        }
      } catch (error) {
        throw error;
      }
    }

    console.log(result);
  };

  if (status !== "authenticated") {
    return (
      <>
        <Head>
          <title>CPETCAM</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <main className={styles.signin_div}>
          <form
            className={styles.signin_form_div}
            action=""
            onSubmit={handleSubmit}
          >
            <img src="/Logo.svg" alt="" height={200} width={200} />

          <div className={styles.signin_form}>
            <div className={styles.input_text_div}>
              <span className={styles.input_span}>Username</span>
              <input
                className={styles.input_text}
                type="text"
                name="text"
                id=""
                value={userInfo.email}
                placeholder="Email/Username"
                onChange={(e) => {
                  setUserInfo({ ...userInfo, text: e.target.value });
                }}
              />
            </div>

            <div className={styles.input_text_div}>
<span className={styles.input_span}>Password</span>

    <input
                  className={styles.input_text}
                  type="password"
                  name="password"
                  id=""
                  value={userInfo.password}
                  placeholder="Password"
                  onChange={(e) => {
                    setUserInfo({ ...userInfo, password: e.target.value });
                  }}
                />
    </div>
    <input
              className={styles.continue_btn}
              type="submit"
              value="Login"
              name="login"
              id=""
            />
            <div className={styles.forgotpass_div}>
              <Link className={styles.forgotpass_link} href="/auth/forgotpass">
                Forgot password?
              </Link>
            </div>



            <p className={styles.p_notfound}>{alert}</p>

            <Link className={styles.continue_btn} href="/auth/signup">
                Sign up
              </Link>
          </div>
          </form>
        </main>
      </>
    );
  } else {
    router.replace("/");
  }
  return <div>Loading</div>;
};

export default signin;
